### ISSUE TITLE
hw04 peer review

### ISSUE THREAD

**Issue by MielleM** [STAT545-UBC-students/hw04-shreeramsenthi#1]
Topic | Excellent | Satisfactory | Needs Work
-- | -- | -- | --
Coding style | x |   |  
Coding strategy | x |   |  
Presentation: graphs | x  |   |  
Presentation: tables | x |   |  
Achievement, creativity |   | x |  
Ease of access | x  |  |  

## Things that worked
- lovely graphs and tables! 
- exploration of the output of different joins was clear, with helpful context + explanation 
- code is well commented when appropriate

## Things to work on
- not something you should have done necessarily, but mapping is pretty easy in ggplot2 if you're ever interested! 

## What I learned
- plotting entries with spaces using  
> ``
Pretty basic, but I had trouble with United States for assignment 3!

**Comment by shreeramsenthi** [comment]
Thanks for the detailed feedback Mielle! I had no idea mapping was an option with ggplot, so I actually wound up trying it out in assignment 5.

Cheers,
Shree
