### ISSUE TITLE
TA comments

### ISSUE THREAD

**Issue by hsmohammed** [STAT545-UBC-students/hw04-shreeramsenthi#2]
Hi Shreeram,

Thanks for your organized homework submission.

# Coding style

Your coding style is very good. You follow coding conventions. My only suggestions is to explain your code more in comments. Use comments at the beginning of every code chunk to explain your objective and the intended functions you will us. Also, use in-line comments when needed to elaborate any functions you see as hard to comprehend.

# Coding strategy

Your coding strategy is efficient and minimal. Your problem solving techniques are very clear to readers.

# Achievement, mastery, cleverness, creativity

Try to think about other out-of-the-box creative problems in future assignments and go above and beyond the required tasks to achieve higher grades. Try to explore other `join` functions for example.

# Ease of access for instructor, compliance with course conventions for submitted work

The code was very accessible and everything runs great.

# Presentation (graphs)

In the life expectancy figure, you should have made a legend that explains what each line/point means.

# Presentation (tables)

Tables are presented in a good way and you used nice visualization styles.

**Comment by shreeramsenthi** [comment]
Thanks for the detailed feedback, I'll be sure to watch for the legends.
